import { Card } from '@interfaces/listing.interface';

export const CardSettings: Card[] = [
  {
    percent: 3.03,
    category: 'Beauty',
    name: 'Nisha',
    surname: 'Lamba',
    instagram: '1.8 M',
    facebook: '562k',
    tikTok: '2.5 M',
    youTube: '384k',
    city: 'Delhi',
    country: 'India',
    img: '//en/assets/png/card-filter.png',
  },
  {
    percent: 2.5,
    category: 'Fashion',
    name: 'John',
    surname: 'Doe',
    instagram: '2.1 M',
    facebook: '750k',
    tikTok: '3.2 M',
    youTube: '500k',
    city: 'New York',
    country: 'USA',
    img: '//en/assets/png/test-filter.png',
  },
  {
    percent: 2.5,
    category: 'Fashion',
    name: 'John',
    surname: 'Doe',
    instagram: '2.1 M',
    facebook: '750k',
    tikTok: '3.2 M',
    youTube: '500k',
    city: 'New York',
    country: 'USA',
    img: '//en/assets/png/test-filter.png',
  },
  {
    percent: 2.5,
    category: 'Fashion',
    name: 'John',
    surname: 'Doe',
    instagram: '2.1 M',
    facebook: '750k',
    tikTok: '3.2 M',
    youTube: '500k',
    city: 'New York',
    country: 'USA',
    img: '//en/assets/png/test-filter.png',
  },
  {
    percent: 3.03,
    category: 'Beauty',
    name: 'Nisha',
    surname: 'Lamba',
    instagram: '1.8 M',
    facebook: '562k',
    tikTok: '2.5 M',
    youTube: '384k',
    city: 'Delhi',
    country: 'India',
    img: '//en/assets/png/card-filter.png',
  },
];
